font_size 21
# font_family TX-02
font_family IoskeleyMono Nerd Font SemiCondensed

enabled_layouts splits

modify_font underline_position +2
modify_font underline_thickness 7%

disable_ligatures never
cursor_trail 3
cursor_trail_start_threshold 20

hide_window_decorations titlebar-only
window_margin_width 2 0 0 2

shell_integration no-title

macos_option_as_alt yes
macos_colorspace displayp3
macos_quit_when_last_window_closed yes

background_blur 100

include theme.conf

kitty_mod cmd

map kitty_mod+enter no_op

map kitty_mod+d launch --location=vsplit --cwd=current
map kitty_mod+shift+d launch --location=hsplit --cwd=current

map kitty_mod+h neighboring_window left
map kitty_mod+j neighboring_window bottom
map kitty_mod+k neighboring_window top
map kitty_mod+l neighboring_window right

map kitty_mod+w close_window

map kitty_mod+1 goto_tab 1
map kitty_mod+2 goto_tab 2
map kitty_mod+3 goto_tab 3
map kitty_mod+4 goto_tab 4
map kitty_mod+5 goto_tab 5
map kitty_mod+6 goto_tab 6
map kitty_mod+7 goto_tab 7
map kitty_mod+8 goto_tab 8
map kitty_mod+9 goto_tab 9
map kitty_mod+0 goto_tab 10
